### ISSUE TITLE
interest

### ISSUE THREAD

**Issue by wardman12345** [XRPLF/xrpl-dev-portal#1053]
there should be a mineable algorithm on the ledger

**Comment by yxxyun** [comment]
I think this can be implemented by hooks. 
https://hooks-testnet.xrpl-labs.com/

**Comment by mDuo13** [comment]
One of the major reasons the XRP Ledger _exists_ is because its creators thought there had to be a better  way than mining. I personally would be strongly against anything that implements mining on the ledger, because [the consequences of wastefully competitive CPU usage](https://xrpl.org/carbon-calculator.html) are significant.

In any case, this repo is not the right place to ask questions or make suggestions about the ledger itself. I suggest https://github.com/ripple/rippled/ (for code-related or implemented suggestions) or https://github.com/XRPLF/XRPL-Standards (for discussions of possible protocol changes, higher-level usage, etc.)
