### ISSUE TITLE
Using With PayString

### ISSUE THREAD

**Issue by ajohnson1031** [XRPLF/xrpl-dev-portal#1140]
I searched everywhere for documentation in this repo concerning using ripple-lib with Paystring. Is it at all possible to submit a transaction in conjunction with PayString?

**Comment by jscottbranson** [comment]
I haven't used ripple-lib in a minute, so there is a chance I'm totally wrong about this.

However, ripple-lib is designed specifically to interact with the XRP Ledger, so, depending on the nature of your project, you would have to use a separate library/script to query PayString endpoints, then pass the resultant XRPL address(es) to ripple-lib.

I think it makes sense for them to keep PayString out of ripple-lib, since PayString is a separate protocol that exists independent from the XRPL.

**Comment by intelliot** [comment]
@crypticrabbit is correct. Yes, you can use PayString, but you'll need to pull in PayString functionality separately.

There are at least a couple options for this:

https://www.npmjs.com/package/@paystring/utils

https://www.npmjs.com/package/payid-lib
