### ISSUE TITLE
Peer Crawler/ Crawl transaction data

### ISSUE THREAD

**Issue by bkalus1** [XRPLF/xrpl-dev-portal#1375]
Any idea how to crawl XRP historic transaction data including fees? Is the peer crawler the correct tool?

**Comment by cjcobb23** [comment]
What exactly do you mean by _crawl_ historic transaction data? You can walk through history at a single node, there is no need to crawl the network for that. S2.ripple.com and xrplcluster.com both provide full history over RPC/websocket.

**Comment by bkalus1** [comment]
Thank you, I meant that I try to generate a data set that includes the public transactions for XRP like time, transaction amount, and fee as listed in the livenet (https://livenet.xrpl.org/)

**Comment by wojake** [comment]
Ye, you can use any library like xrpl-py & xrpl4j to do that, it's quite easy.

**Comment by mDuo13** [comment]
If you want to pull a history of all transactions, the right approach is probably to use the [ledger method](https://xrpl.org/ledger.html) with `"transactions": true` and `"expand": true`. That'll give you a view of every transaction executed in a given ledger block; you can repeat for any and every ledger to get a full view of all transactions (back to the earliest saved ledger, which is 32570 for the XRPL Mainnet. The first two weeks or so of ledger history was lost due to a bug in the server at the time).

Anyway, hope that answers your question. If not, feel free to reopen this issue.
