### ISSUE TITLE
Document maximum (clamped) value of parameter limit in Data API v2

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#139]
Value of parameter limit seems to be clamped, but this is not documented.

For example,

https://data.ripple.com/v2/exchanges/XRP/USD+rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q?interval=1hour&format=csv&limit=100000

returns only 1000 results and you cannot get more results because in this case API doesn't return 'marker'.

**Comment by mDuo13** [comment]
You are correct. I'll add a correction when I get a chance.

**Comment by mDuo13** [comment]
Fixed in this commit:
https://github.com/ripple/ripple-dev-portal/commit/9671287381a77999683b55d14da65b13ba7055a1

Also, I opened two tickets to the Data API project as a result here:
- [RD-832](https://ripplelabs.atlassian.net/browse/RD-832) to add limits to the currently unlimited methods
- [RD-833](https://ripplelabs.atlassian.net/browse/RD-833) to add a way to do pagination with CSV responses
