### ISSUE TITLE
Mobile search is unusable

### ISSUE THREAD

**Issue by ledhed2222** [XRPLF/xrpl-dev-portal#1465]
https://user-images.githubusercontent.com/7291533/184242707-ce4819dc-d657-4c88-8f40-39a0e14e20b2.MOV

See above video. With multiple results of search on mobile there is no way to scroll through them. The focus is wrong or something

**Comment by ledhed2222** [comment]
https://user-images.githubusercontent.com/7291533/184243287-78ae40f2-ba55-4921-817c-4db9ceae88e8.MOV



Also see above. If you manage to enter your search, close the keyboard, open the text input again to reveal the keyboard, then hit enter, you can see a list of results. 1) that's a very unintuitive flow and 2) once you get there again due to z-indexing or something, you cannot scroll through the results instead scrolling through the background page.

**Comment by mDuo13** [comment]
I'm not sure we can fix this, because the search is powered by an external service (Algolia DocSearch) that we have very little control over, and may not be worth it because we are planning to move to a new architecture, including a different search provider, sometime around the end of this year (or maybe early next year?)

**Comment by intelliot** [comment]
As a workaround, I tend to just search with plain Google and just tack `xrpl` or `site:xrpl.org` onto my query. It works well.
