### ISSUE TITLE
NFT doc discrepancies

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1487]
As originally reported by @Silkjaer:

> https://xrpl.org/nftokenpage.html - Example uses Tokens for the page content, the documentation uses NonFungibleTokens, but the actual key is NFTokens – also the example content is a bit off, as it's actually an array like the screenshot attached
> ![screenshot](https://user-images.githubusercontent.com/7515597/187972802-c5ff4dc2-d9d5-4579-a38d-91730d753641.png)
>
> There is a discrepancy between https://github.com/XRPLF/XRPL-Standards/discussions/46 and https://xrpl.org/nftokenoffer.html regarding the flag of an NFTokenOffer `0x00000001`. Documentation says its a `lsfBuyToken` flag and if not set, it's a sell offer. XLS20 says the exact opposite, its a `lsfSellToken`. `LedgerFormats.h` says its a `lsfSellNFToken` (so updated to NFToken naming convention and agrees with standard, but not documentation. But what is the flag actually?
>
> On the same page, documentation refers to lsfAuthorized which i think is not part of the implemententation? 
>
> https://xrpl.org/nftokencanceloffer.html refers to TokenOffers but should be NFTokenOffers

**Comment by Silkjaer** [comment]
Elaborating on the original post, I have made a more thorough walkthrough of the documentation related to NFTokens and here's an updated list organized by page:

### https://xrpl.org/nftoken.html

- `TokenID` should be `NFTokenID` (multiple occurrences)
- Could consider using `NFTokenTaxon` instead of `Taxon`, as that is specified in the NFTokenMint transaction. 

### https://xrpl.org/nftokenoffer.html

- `TokenID` should be `NFTokenID`
- `lsfAuthorized` is not implemented and should be removed from documentation
- `lsfBuyToken` should be `lsfSellNFToken` with this description: `If set, indicates that the offer is a sell offer. Otherwise, the offer is a buy offer.`
- `NFTokenOfferNode` is missing

### https://xrpl.org/nftokenpage.html

- The example data structure needs to change to reflect the implementation (see OP)
- `NonFungibleTokens` should be `NFTokens`

### https://xrpl.org/nftokenacceptoffer.html

- `NFT` should be `NFToken`
- `TransferRate` should be `TransferFee` 

### https://xrpl.org/nftokencanceloffer.html

- `TokenOffers` should be `NFTokenOffers`

### https://xrpl.org/nftokencreateoffer.html

- `tfSellToken` should be `tfSellNFToken`

### https://xrpl.org/nftokenmint.html

- First example should probably be simpler – not showing a case of issuing on behalf of another account as there is an example for that later on the same page.

**Comment by mDuo13** [comment]
Just checked, and all of the issues have been addressed by https://github.com/XRPLF/xrpl-dev-portal/pull/1510
