### ISSUE TITLE
Allow the use of different server in API tools

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#154]
For example, on

https://ripple.com/build/rest-tool/#sign-transaction

it should be possible to change the server address (to testnet server, for example).

**Comment by mDuo13** [comment]
This already exists as a "hidden feature" in all the REST-based API tools. For example:
https://ripple.com/build/rest-tool/?base_url=https://api.altnet.rippletest.net:5990

It will only work if the corresponding server uses the appropriate CORS settings.

The version of the `rippled` WebSocket API Tool included in the Dev Portal code has the same feature (also the optional query parameter ?use_wss=false to use non-secure websockets if, for example, you're hosting ws: on a localhost `rippled` machine) but the feature is not available on ripple.com because it tends to be unreliable, especially at indicating whether it's connected properly or not.
