### ISSUE TITLE
TicketSequence in DepositPreauth is undocumented

### ISSUE THREAD

**Issue by donovanhide** [XRPLF/xrpl-dev-portal#1574]
https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/impl/TxFormats.cpp#L272
https://xrpl.org/depositpreauth.html#depositpreauth-fields

**Comment by mDuo13** [comment]
This is already documented correctly although it's unintuitive because the implementation is quirky.

TicketSequence is implemented as a "type-specific" field on _every_ non-pseudo-transaction type. In the documentation we have chosen to define it once in the [common fields](https://xrpl.org/transaction-common-fields.html) instead.
