### ISSUE TITLE
Update Ubuntu build instructions

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1651]
Just recently the steps needed to [build rippled on Ubuntu](https://xrpl.org/build-run-rippled-ubuntu.html) changed (starting with dev versions of 1.10.0) to use Conan to manage packages. This means changes to the build instructions.

Upstream PR: https://github.com/XRPLF/rippled/pull/4367
Related: #1650, #1648.

Add any new dependencies and modify the steps as necessary to build on supported (current) versions of Ubuntu.

## Aside: future of build instructions

It has been previously discussed, and might still be a good idea, to remove the separate build instructions on the xrpl website and only link [the instructions in the source repo](https://github.com/XRPLF/rippled/tree/develop/Builds), since the method of building is specific to the release version. The repo also has build instructions for more platforms. We would like to first make sure the build instructions in the repo are clear and easy enough to follow, though, which might mean making PRs against the `rippled` repo to update them there.

There's also the consideration that the website has Japanese-translated build instructions, which aren't kept _perfectly_ up-to-date with the English but are probably better than nothing for native Japanese speakers; so we might want to port those to the upstream repo as well, but the team may not want to be responsible for those since they it would probably require someone fluent in Japanese to keep things updated as well.

**Comment by thejohnfreeman** [comment]
I prefer to link to the new build instructions in the root directory of the project, in the conventionally named file [`BUILD.md`](https://github.com/XRPLF/rippled/blob/develop/BUILD.md).

I would like to collaborate on fixing up the build instructions in the repository:

- I believe that, under the directory `Builds/`, the directories `VisualStudio2019`, `linux`, and `macos` can be removed. In fact, I believe they contain currently incorrect documentation, on top of being elaborate and confusing. I suspect that `Test.py` and `build_all.sh` are unused and can be removed.
- We should move and update documentation on the project options from `Builds/linux/README.md` to `BUILD.md`.
- I'd like a review from technical writers on the structure of `BUILD.md`. We're trying to serve a few different audiences:
  - Maintainers who are responsible for keeping these instructions up-to-date. It's better to have them all in one file, instead of just-slightly-different-but-mostly-identical instructions in separate files and directories for each platform.
  - Experienced developers who just need to reference the commands, and maybe copy them.
  - New developers who need a walk through, including an introduction to Conan and CMake.

I think it's totally fine to add a Japanese translation to the source repo. Perhaps we can add a note at the top to warn readers to check the difference between the last time the English and Japanese versions were changed.

**Comment by intelliot** [comment]
I recommend deleting what's on xrpl.org (as it's out of date / obsolete anyway) and pointing people to instructions in rippled repo.
