### ISSUE TITLE
Documentation Links Are Dead (Easy Fix) (Bug)

### ISSUE THREAD

**Issue by Codie-Petersen** [XRPLF/xrpl-dev-portal#1810]
There are a lot of links that are dead in the documentation. I suspect there was a reorg for the folder structure or reformatting of the documentation. For example, in the [public-api-methods](https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/references/http-websocket-apis/public-api-methods/public-api-methods.md) many of the links do not work, possibly all of them. I can just search for them in the repo, but still. Figured you'd like to know.

Might be a good idea to bake link checking into your CI/CD pipeline. Not sure what you guys are using, but a markdown 404 link checker would be pretty easy to make if it doesn't already exist.

**Comment by mDuo13** [comment]
I think you may be browsing the source files in the source repository, rather than viewing them on the actual xrpl.org website? That's not how they're intended to be used, and those links aren't expected to work in that context. The links on https://xrpl.org/public-api-methods.html , which is built from that file, _do_ work just fine.

Aside from the links, there are various formatting things that only work when the site is built the intended way. That's just a consequence of the authoring tools we use.
