### ISSUE TITLE
XRPFees Fields Reverted

### ISSUE THREAD

**Issue by jscottbranson** [XRPLF/xrpl-dev-portal#1940]
I believe there are inconsistencies in the docs regarding the XRPFees amendment, since the amendment would have originally changed the field names to end in "Drops" (e.g., BaseFee vs BaseFeeDrops).

@mvadari pointed out that those changes were reverted [in PR 4429](https://github.com/XRPLF/rippled/pull/4429) before the amendment was merged.

Thus, I believe the [known amendment description](https://xrpl.org/known-amendments.html#xrpfees) needs to be updated as does the [documentation](https://xrpl.org/setfee.html#setfee-fields) on the `SetFee` fields.

**Comment by ckniffen** [comment]
Those field names were still changed.  What didn't change was RPC calls and validation streams.  If you are evaluating the SetFee transaction or looking at the FeeSettings ledger object and doing stuff with that then you will need to still update.

Since SetFee only is created during consensus we lowered the priority of updating the client libraries for it.  The explorer has been update here. https://github.com/ripple/explorer/pull/605/files#diff-8c52e1cf259431d58ac697d339550d55477b537d7daddc3f9acc61dfd5c1715a.

Related issues:
https://github.com/XRPLF/xrpl.js/issues/2219
https://github.com/XRPLF/xrpl-py/issues/526

**Comment by ckniffen** [comment]
I am working on adding the new types to the JS.  One thing that was uncovered is clio does not work after this amendment is enabled.  https://github.com/XRPLF/clio/issues/709
