### ISSUE TITLE
If the xrp ledger has the historical blockdata snapshot?

### ISSUE THREAD

**Issue by qiangjiyi** [XRPLF/xrpl-dev-portal#1998]
Hi,

I'm a blockchain engineer, Our company plans to build a comprehensive blockchain explorer based on the Xrp ledger. So we need all historical blockdata from the genesis block to the present. However, we have been unable to find any historical blockdata snapshots. 

Synchronizing all the historical data directly would take too long. Is there a better solution available?

**Comment by mDuo13** [comment]
You don't actually need all historical data to make an explorer for the ledger, since each new ledger block contains a snapshot of the current settings and balances.

If you _do_ need full history, see [Configure Full History](https://xrpl.org/configure-full-history.html) for instructions. I believe the disk requirements are up to ~23 TB now. If you're looking for someone who can share a database dump with a lot of history, 

You could also [use the BigQuery dataset](https://www.youtube.com/watch?v=lzyytL8VImo) for some stuff. I don't have much familiarity with it, though.

Feel free to reopen if this doesn't answer your question.
