### ISSUE TITLE
Update JS/TS SDK AMM Swap Example

### ISSUE THREAD

**Issue by aetherplex** [XRPLF/xrpl-dev-portal#2616]
Could be a me issue, but I can't get the swapping to work as outlined in the `amm.ts` example. Based on the TS typings the structure of the `Paths` objects has changed (the `type` field has been deprecated) and removing the `type` field doesn't fix it. @mDuo13 it looks like you were the last to update this, can you please help me out?

**Comment by mDuo13** [comment]
I'm not the right person, since all I did is move the files to a different folder when we changed doc toolchains.

Before that, the ts files were added by @mashharuki in #2307.

I am not aware of any changes to the `Paths` object typing, so unless there's some sort of change in the [xrpl.js library](https://github.com/XRPLF/xrpl.js/) then I am guessing the problem is elsewhere.

**Comment by aetherplex** [comment]
Thanks @mDuo13. @mahnunchik any chance you could please take a look at our repo? I can invite you to our repo to triage 

Edit: managed to get it working on devnet. Might be an issue with testnet or we just missed a step

**Comment by ckeshava** [comment]
Hello, do you happen to remember the error details when you observed the issue?
The testnet faucet was down for a brief time yesterday -- perhaps, that might have been the issue.
