### ISSUE TITLE
i have facing a new issue in rippled

### ISSUE THREAD

**Issue by vigneshindn** [XRPLF/xrpl-dev-portal#707]
Error from accout status
========================

```
root@ripple_wallet:/home/ubuntu# rippled -- account_tx nnnnnnnnnnnnnnnnnnnN
{
   "result" : {
      "error" : "lgrIdxsInvalid",
      "error_code" : 57,
      "error_message" : "Ledger indexes invalid.",
      "request" : {
         "account" : "nnnnnnnnnnnnnnnnnnnnnN",
         "command" : "account_tx"
      },
      "status" : "error"
   }
}
```

---

```
server_info 
........
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "nhfkdjhkdjshfkhkjhsaajhkjfhkshkfjkshfkjhakhfkhfoewiwuorwqrry21wqqwA",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "server_state_duration_us" : "441594813",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "441594813",
               "transitions" : 1
..........
.........
         "time" : "2019-Oct-25 14:46:13.403900",
         "uptime" : 443,
         "validation_quorum" : 28,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2019-Dec-10 00:00:00.000000000",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}
```

---

am using 16 gb ram and 8 core processer and 100 gb storage.

_(Note: I've edited the formatting to make this display better. --@mDuo13)_

**Comment by mDuo13** [comment]
The error message you're getting is because your server isn't synced to the network.

https://github.com/ripple/xrpl-dev-portal/pull/713/commits/f3db1cd141b23183cbb07ccc54465e19e59a9ada improves the documentation for this error message.

As for why your server isn't syncing with the network, the most common cause is not meeting the [system requirements](https://xrpl.org/system-requirements.html), specifically disk I/O. There are other possible causes as well. Sometimes the server doesn't have enough peers to download the current ledger state. (You have exactly 10 peers, which suggests that your firewall is blocking inbound peer connections, so fixing that might help.) Sometimes just restarting the server fixes the problem. For other cases, see the [rippled issues](https://github.com/ripple/rippled/issues?q=is%3Aissue+is%3Aopen+label%3A%22Syncing+issue%22).
