### ISSUE TITLE
I want to delete my XRP wallet and take back my XPR deposited.

### ISSUE THREAD

**Issue by harshvardhan-shah** [XRPLF/xrpl-dev-portal#912]
I am totally disappointed with XRP and I want to take back my XRP but it still holds 20 XRP for no apparent reason. If you can activate account with 20 XRP, why can't you deactivate it when it is empty???

I want nothing but delete my wallet and recover my XRP to an exchange.

**Comment by dangell7** [comment]
Did you get help?

**Comment by harshvardhan-shah** [comment]
> Did you get help?

NO.

**Comment by ximinez** [comment]
We generally don't look for technical support questions in this repository, which holds the documentation related to the XRP ledger. More appropriate repositories include https://github.com/ripple/rippled and https://github.com/ripple/ripple-lib, depending on how you're interacting with the ledger.

In any case, it sounds like you want to delete your account. The transaction for that is documented at https://xrpl.org/accountdelete.html#accountdelete

I'm going to close this issue, since I believe this answers your question. If you have any further questions or issues, please open a new issue in the appropriate repository.
